/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 7ec7f28e71a2531f8c2e286e4a4d4da8c791e771 */

static void register_fb_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("FB_LAYOUT_MONO_ROWS", FB_LAYOUT_MONO_ROWS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_MONO_PAGES", FB_LAYOUT_MONO_PAGES, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_INDEX2", FB_LAYOUT_INDEX2, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_INDEX4", FB_LAYOUT_INDEX4, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_INDEX8", FB_LAYOUT_INDEX8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_RGB444", FB_LAYOUT_RGB444, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_RGB565", FB_LAYOUT_RGB565, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_RGB666", FB_LAYOUT_RGB666, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_RGB888", FB_LAYOUT_RGB888, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_RGBA8888", FB_LAYOUT_RGBA8888, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_LAYOUT_PLANAR", FB_LAYOUT_PLANAR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_BIT_ORDER_MSB", FB_BIT_ORDER_MSB, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_BIT_ORDER_LSB", FB_BIT_ORDER_LSB, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_BYTE_ORDER_MSB", FB_BYTE_ORDER_MSB, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_BYTE_ORDER_LSB", FB_BYTE_ORDER_LSB, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_CHANNELS_RGB", FB_CHANNELS_RGB, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_CHANNELS_BGR", FB_CHANNELS_BGR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_CHANNELS_RGBA", FB_CHANNELS_RGBA, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_CHANNELS_BGRA", FB_CHANNELS_BGRA, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_CHANNELS_ARGB", FB_CHANNELS_ARGB, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_CHANNELS_ABGR", FB_CHANNELS_ABGR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_SCAN_TOP_DOWN", FB_SCAN_TOP_DOWN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("FB_SCAN_BOTTOM_UP", FB_SCAN_BOTTOM_UP, CONST_PERSISTENT);
}
